version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  setup:
    docker:
      - image: circleci/node:12.19.0-browsers
    steps:
      - checkout
      - node/install-npm
      - run: node --version
      - run: npm --version
      - node/install-packages
      - run: npm test -- --coverage --watchAll=false
      - run: npm chromatic --project-token 7jg1cd7ny4

workflows:
  ci:
    jobs:
      - setup
